apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-eyci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-eyci
    app.kubernetes.io/part-of: test-app-bveu
  name: test-component-eyci
  namespace: build-e2e-ozcb-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-eyci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-eyci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:47c394b1e1be36af7e65848686855d502ddfd2d95391d2319e93f25ad7fae13b
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
